#!/bin/bash

natom=20900
header=16

tail -$natom trj > t
sort -nk1 < t> tt
awk '{print ($2,$4,$5,$6)}' < tt> ttt1

tail -$natom trjvel > t
sort -nk1 < t> tt
awk '{print ($3,$4,$5)}' < tt> ttt2

head -$header data.rdx > rebuild_data_lammps

first=$(( header + 1 ))
end=$(( header + natom ))
sed -n $first,"$end"p data.rdx > temp1
awk '{print ($1,$2, "  ")}' < temp1 > temp2
paste temp2 ttt1 > temp3
cat temp3 >> rebuild_data_lammps

echo "   " >> rebuild_data_lammps
echo "Velocities" >> rebuild_data_lammps
echo "   " >> rebuild_data_lammps

first=$(( header + 1 + 3 + natom ))
end=$(( first + natom ))
sed -n $first,"$end"p data.rdx > temp1
awk '{print ($1, "  ")}' < temp1 > temp2
paste temp2 ttt2 > temp3
cat temp3 >> rebuild_data_lammps


rm -f t tt ttt* temp*
